command /loc <number>:
  trigger:
    player is op
    set {loc.%arg 1%} to location of player
    message "%arg 1% set to your location."
command /testloc <number>:
  trigger:
    player is op
    teleport player to {loc.%arg 1%}
on script load:
  set {gamemode} to "sheepquest"
  wait 5 seconds
  if {gamemode} is "sheepquest":
    spawn a blue sheep named "&bBlue Team"
    teleport last spawned sheep to {loc.1}
  
